In [1]:
import pandas as pd 
import numpy as np
import random

In [3]:
ods_file="/home/manik/Downloads/FakeAvCelebPreprocessed/df_matching_frames.csv"
df = pd.read_csv(ods_file)
df.head()

,source,method,category,type,race,gender,path,split,full_path,num_frames,duration,difference
0,id00076,real,A,RealVideo-RealAudio,African,men,00109.mp4,train,/home/manik/Downloads/FakeAvCelebPreprocessed/...,251,10.048,0
1,id00166,real,A,RealVideo-RealAudio,African,men,00010.mp4,test,/home/manik/Downloads/FakeAvCelebPreprocessed/...,160,6.400,0
2,id00173,real,A,RealVideo-RealAudio,African,men,00118.mp4,train,/home/manik/Downloads/FakeAvCelebPreprocessed/...,149,6.016,0
3,id00366,real,A,RealVideo-RealAudio,African,men,00118.mp4,train,/home/manik/Downloads/FakeAvCelebPreprocessed/...,224,8.960,0
4,id00391,real,A,RealVideo-RealAudio,African,men,00052.mp4,val,/home/manik/Downloads/FakeAvCelebPreprocessed/...,300,12.032,0

In [4]:
df[df['num_frames']==0]

Empty DataFrame
Columns: [source, method, category, type, race, gender, path, split, full_path, num_frames, duration, difference]
Index: []

In [57]:
df.iloc[0]["full_path"]

'/home/manik/Downloads/FakeAvCelebPreprocessed/RealVideo-RealAudio/African/men/id00076/00109.mp4'

In [60]:
df[df["full_path"]=="/home/manik/Downloads/FakeAvCelebPreprocessed/FakeVideo-FakeAudio/African/men/id00076/00109_2_id00166_wavtolip.mp4"]

,source,method,category,type,race,gender,path,split,full_path,num_frames,duration
1737,id00076,faceswap-wav2lip,D,FakeVideo-FakeAudio,African,men,00109_2_id00166_wavtolip.mp4,train,/home/manik/Downloads/FakeAvCelebPreprocessed/...,102,4.224

In [3]:
ods_file2="/home/manik/Downloads/FakeAVCeleb_v1.2/meta_data.csv"
df_real = pd.read_csv(ods_file2)
df_real.head()

,source,target1,target2,method,category,type,race,gender,path,full_path
0,id00076,-,-,real,A,RealVideo-RealAudio,African,men,00109.mp4,FakeAVCeleb/RealVideo-RealAudio/African/men/id...
1,id00166,-,-,real,A,RealVideo-RealAudio,African,men,00010.mp4,FakeAVCeleb/RealVideo-RealAudio/African/men/id...
2,id00173,-,-,real,A,RealVideo-RealAudio,African,men,00118.mp4,FakeAVCeleb/RealVideo-RealAudio/African/men/id...
3,id00366,-,-,real,A,RealVideo-RealAudio,African,men,00118.mp4,FakeAVCeleb/RealVideo-RealAudio/African/men/id...
4,id00391,-,-,real,A,RealVideo-RealAudio,African,men,00052.mp4,FakeAVCeleb/RealVideo-RealAudio/African/men/id...

In [6]:
extra_rows = df_real[~df_real['path'].isin(df['path'])]
extra_rows
# Keep only rows whose 'path' exists in df_ref
df_real = df_real[df_real['path'].isin(df['path'])].reset_index(drop=True)

In [7]:
extra_rows = df_real[~df_real['path'].isin(df['path'])]
extra_rows

Empty DataFrame
Columns: [source, target1, target2, method, category, type, race, gender, path, full_path]
Index: []

In [8]:
import os
import cv2
import pandas as pd

root_dir = "/home/manik/Downloads/FakeAVCeleb_v1.2"  # <-- change this

def get_num_frames(row):
    try:
        # Build full path
        video_path = os.path.join(
            root_dir,
            row["type"],
            row["race"],
            row["gender"],
            row["source"],
            row["path"]
        )

        # Read video
        cap = cv2.VideoCapture(video_path)
        if not cap.isOpened():
            return None
        
        frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
        cap.release()
        return frames
    except Exception:
        return None  # handle invalid or missing files

# Apply to each row
df_real["num_frames"] = df_real.apply(get_num_frames, axis=1)

In [9]:
df_real.head()

,source,target1,target2,method,category,type,race,gender,path,full_path,num_frames
0,id00076,-,-,real,A,RealVideo-RealAudio,African,men,00109.mp4,FakeAVCeleb/RealVideo-RealAudio/African/men/id...,251
1,id00166,-,-,real,A,RealVideo-RealAudio,African,men,00010.mp4,FakeAVCeleb/RealVideo-RealAudio/African/men/id...,160
2,id00173,-,-,real,A,RealVideo-RealAudio,African,men,00118.mp4,FakeAVCeleb/RealVideo-RealAudio/African/men/id...,149
3,id00366,-,-,real,A,RealVideo-RealAudio,African,men,00118.mp4,FakeAVCeleb/RealVideo-RealAudio/African/men/id...,224
4,id00391,-,-,real,A,RealVideo-RealAudio,African,men,00052.mp4,FakeAVCeleb/RealVideo-RealAudio/African/men/id...,300

In [10]:
df_real.describe()

         num_frames
count  21563.000000
mean     131.699253
std       48.783288
min       23.000000
25%      102.000000
50%      118.000000
75%      147.000000
max      442.000000

In [18]:
df['difference']=df['num_frames']-df_real['num_frames']

In [32]:
df[df['difference']!=0]['difference']

1055    -8
1100    -2
3207    -1
3210    -1
7127   -24
7128   -14
7130   -34
7131   -34
7133   -29
7134   -29
7135    -1
8184   -25
8185   -55
8186   -34
8187   -36
8188   -42
8189   -38
8190   -57
8191   -37
8208    -3
8210    -6
8211    -3
8212    -4
8213    -7
8215    -4
Name: difference, dtype: int64

In [ ]:
df_matching_frames=df[df['difference']==0]

(21538, 12)

In [37]:
df_matching_frames.head()

,source,method,category,type,race,gender,path,split,full_path,num_frames,duration,difference
0,id00076,real,A,RealVideo-RealAudio,African,men,00109.mp4,train,/home/manik/Downloads/FakeAvCelebPreprocessed/...,251,10.048,0
1,id00166,real,A,RealVideo-RealAudio,African,men,00010.mp4,test,/home/manik/Downloads/FakeAvCelebPreprocessed/...,160,6.400,0
2,id00173,real,A,RealVideo-RealAudio,African,men,00118.mp4,train,/home/manik/Downloads/FakeAvCelebPreprocessed/...,149,6.016,0
3,id00366,real,A,RealVideo-RealAudio,African,men,00118.mp4,train,/home/manik/Downloads/FakeAvCelebPreprocessed/...,224,8.960,0
4,id00391,real,A,RealVideo-RealAudio,African,men,00052.mp4,val,/home/manik/Downloads/FakeAvCelebPreprocessed/...,300,12.032,0

In [36]:
print(df_real.shape)
print(df_matching_frames.shape)

(21563, 11)
(21538, 12)

In [34]:
df_matching_frames['num_frames'].describe()

count    21538.000000
mean       131.670211
std         48.747721
min         23.000000
25%        102.000000
50%        118.000000
75%        147.000000
max        442.000000
Name: num_frames, dtype: float64

In [46]:
df_matching_frames.shape

(21538, 12)

In [47]:
df_matching_frames.to_csv("/home/manik/Downloads/FakeAvCelebPreprocessed/df_matching_frames.csv", index=False)

In [39]:
df_matching_frames.head()

,source,method,category,type,race,gender,path,split,full_path,num_frames,duration,difference
0,id00076,real,A,RealVideo-RealAudio,African,men,00109.mp4,train,/home/manik/Downloads/FakeAvCelebPreprocessed/...,251,10.048,0
1,id00166,real,A,RealVideo-RealAudio,African,men,00010.mp4,test,/home/manik/Downloads/FakeAvCelebPreprocessed/...,160,6.400,0
2,id00173,real,A,RealVideo-RealAudio,African,men,00118.mp4,train,/home/manik/Downloads/FakeAvCelebPreprocessed/...,149,6.016,0
3,id00366,real,A,RealVideo-RealAudio,African,men,00118.mp4,train,/home/manik/Downloads/FakeAvCelebPreprocessed/...,224,8.960,0
4,id00391,real,A,RealVideo-RealAudio,African,men,00052.mp4,val,/home/manik/Downloads/FakeAvCelebPreprocessed/...,300,12.032,0

In [49]:
df_path = "/home/manik/Downloads/FakeAvCelebPreprocessed/df_matching_frames.csv"              # your DataFrame CSV file
df= pd.read_csv(df_path)
df.shape

(21538, 12)

In [50]:
import os
import pandas as pd
import subprocess
import numpy as np
import soundfile as sf
from concurrent.futures import ProcessPoolExecutor, as_completed
from tqdm import tqdm


# ============================================================
# CONFIG
# ============================================================
rootdir = "/home/manik/Downloads/FakeAVCeleb_v1.2"              # base dir containing videos
audio_root = "/home/manik/Downloads/alligned_audio"     # base dir to save aligned audios
df_path = "/home/manik/Downloads/FakeAvCelebPreprocessed/df_matching_frames.csv"              # your DataFrame CSV file
sample_rate = 16000                       # Hz
fps = 25                                 # video frame rate
num_workers = 8                           # parallel workers


# ============================================================
# 1️⃣ LOAD DATAFRAME AND BUILD FULL PATHS
# ============================================================
df = pd.read_csv(df_path)

# build full video paths
df["full_path"] = df.apply(
    lambda r: os.path.join(
        rootdir,
        str(r["type"]),
        str(r["race"]),
        str(r["gender"]),
        str(r["source"]),
        str(r["path"])
    ),
    axis=1
)

# build output audio root folder keeping structure
df["audio_folder"] = df.apply(
    lambda r: os.path.join(
        audio_root,
        str(r["type"]),
        str(r["race"]),
        str(r["gender"]),
        str(r["source"])
    ),
    axis=1
)

# ensure folders exist
for folder in df["audio_folder"].unique():
    os.makedirs(folder, exist_ok=True)


# ============================================================
# 2️⃣ HELPER FUNCTIONS
# ============================================================
def get_video_duration(video_path):
    """Get duration (in seconds) using ffprobe"""
    cmd = [
        "ffprobe", "-v", "error", "-show_entries", "format=duration",
        "-of", "default=noprint_wrappers=1:nokey=1", video_path
    ]
    return float(subprocess.check_output(cmd).decode().strip())


def extract_aligned_audio(video_path):
    """Return time-aligned audio matching video duration, zero-filled"""
    duration = get_video_duration(video_path)
    expected_samples = int(duration * sample_rate)

    # extract raw audio
    cmd = [
        "ffmpeg", "-i", video_path, "-f", "f32le", "-acodec", "pcm_f32le",
        "-ac", "1", "-ar", str(sample_rate), "-"
    ]
    try:
        raw = subprocess.check_output(cmd, stderr=subprocess.DEVNULL)
        audio_data = np.frombuffer(raw, np.float32)
    except subprocess.CalledProcessError:
        audio_data = np.zeros(0, np.float32)

    # pad or truncate to match video duration
    audio = np.zeros(expected_samples, dtype=np.float32)
    n = min(len(audio_data), expected_samples)
    audio[:n] = audio_data[:n]
    return audio, duration


def process_row(row):
    """Extract aligned audio and save frame-based segments"""
    video_path = row["full_path"]
    out_folder = row["audio_folder"]
    base = os.path.splitext(os.path.basename(row["path"]))[0]

    try:
        audio, duration = extract_aligned_audio(video_path)
    except Exception as e:
        return f"❌ {base}: {e}"

    samples_per_frame = int(sample_rate / fps)
    num_frames = int(duration * fps)

    for i in range(num_frames):
        start = i * samples_per_frame
        end = start + samples_per_frame
        seg = audio[start:end]

        if len(seg) < samples_per_frame:
            seg = np.pad(seg, (0, samples_per_frame - len(seg)))

        out_path = os.path.join(out_folder, f"{base}_frame{i:05d}.wav")
        sf.write(out_path, seg, sample_rate)

    return f"✅ {base} ({num_frames} segments)"


# ============================================================
# 3️⃣ PARALLEL PROCESSING WITH PROGRESS BAR
# ============================================================
if __name__ == "__main__":
    print(f"Processing {len(df)} videos using {num_workers} workers...\n")

    with ProcessPoolExecutor(max_workers=num_workers) as executor:
        futures = [executor.submit(process_row, row) for _, row in df.iterrows()]

        for f in tqdm(as_completed(futures), total=len(futures), desc="Extracting audio", ncols=90):
            result = f.result()
            tqdm.write(result)

    print("\n🎯 All videos processed successfully!")

Extracting audio: 100%|████████████████████████████▉| 21480/21538 [52:05<00:07,  7.43it/s]

✅ 00083_id02089_wavtolip (181 segments)
✅ 00083_id06428_wavtolip (124 segments)
✅ 00083_id07236_wavtolip (90 segments)

Extracting audio: 100%|████████████████████████████▉| 21482/21538 [52:05<00:08,  6.42it/s]

✅ 00405_id00235_wavtolip (86 segments)
✅ 00405_id00417_wavtolip (96 segments)

Extracting audio: 100%|████████████████████████████▉| 21484/21538 [52:05<00:06,  7.88it/s]

✅ 00083_id07008_wavtolip (132 segments)
✅ 00405_id02089_wavtolip (106 segments)
✅ 00405_id03559_wavtolip (106 segments)

Extracting audio: 100%|████████████████████████████▉| 21487/21538 [52:06<00:06,  8.34it/s]

✅ 00405_id05931_wavtolip (72 segments)
✅ 00405_id05435_wavtolip (94 segments)

Extracting audio: 100%|████████████████████████████▉| 21488/21538 [52:06<00:06,  8.22it/s]

✅ 00405_id04529_wavtolip (106 segments)

Extracting audio: 100%|████████████████████████████▉| 21489/21538 [52:06<00:08,  5.84it/s]

✅ 00405_id07236_wavtolip (90 segments)
✅ 00405_id06439_wavtolip (106 segments)

Extracting audio: 100%|████████████████████████████▉| 21491/21538 [52:06<00:07,  5.97it/s]

✅ 00405_id07377_wavtolip (106 segments)

Extracting audio: 100%|████████████████████████████▉| 21494/21538 [52:07<00:05,  7.33it/s]

✅ 00052_id06232_wavtolip (84 segments)
✅ 00052_id00739_wavtolip (123 segments)
✅ 00052_id04070_wavtolip (143 segments)

Extracting audio: 100%|████████████████████████████▉| 21494/21538 [52:07<00:05,  7.33it/s]

✅ 00052_id06439_wavtolip (111 segments)

Extracting audio: 100%|████████████████████████████▉| 21498/21538 [52:07<00:05,  7.23it/s]

✅ 00052_id07008_wavtolip (132 segments)
✅ 00052_id06752_wavtolip (146 segments)
✅ 00052_id04582_wavtolip (211 segments)

Extracting audio: 100%|████████████████████████████▉| 21498/21538 [52:08<00:05,  7.23it/s]

✅ 00052_id07689_wavtolip (98 segments)
✅ 00143_id04530_wavtolip (74 segments)

Extracting audio: 100%|████████████████████████████▉| 21503/21538 [52:08<00:03,  9.06it/s]

✅ 00052_id07051_wavtolip (166 segments)
✅ 00143_id04529_wavtolip (115 segments)
✅ 00052_id07377_wavtolip (154 segments)

Extracting audio: 100%|████████████████████████████▉| 21509/21538 [52:09<00:02, 10.01it/s]

✅ 00143_id04582_wavtolip (132 segments)
✅ 00143_id05478_wavtolip (132 segments)
✅ 00143_id06439_wavtolip (112 segments)
✅ 00143_id06268_wavtolip (132 segments)
✅ 00025_id01026_wavtolip (85 segments)
✅ 00143_id07689_wavtolip (98 segments)
✅ 00143_id07008_wavtolip (132 segments)

Extracting audio: 100%|████████████████████████████▉| 21511/21538 [52:09<00:03,  8.11it/s]

✅ 00025_id02310_wavtolip (135 segments)
✅ 00025_id03897_wavtolip (90 segments)

Extracting audio: 100%|████████████████████████████▉| 21515/21538 [52:09<00:02,  9.22it/s]

✅ 00025_id04490_wavtolip (96 segments)
✅ 00025_id06254_wavtolip (99 segments)
✅ 00025_id06438_wavtolip (96 segments)
✅ 00025_id07236_wavtolip (90 segments)

Extracting audio: 100%|████████████████████████████▉| 21517/21538 [52:09<00:01, 10.60it/s]

✅ 00025_id06437_wavtolip (123 segments)

Extracting audio: 100%|████████████████████████████▉| 21522/21538 [52:10<00:01, 10.94it/s]

✅ 00254_id05434_wavtolip (47 segments)
✅ 00025_id07051_wavtolip (166 segments)
✅ 00025_id07686_wavtolip (119 segments)
✅ 00254_id00417_wavtolip (95 segments)
✅ 00254_id03897_wavtolip (90 segments)

Extracting audio: 100%|████████████████████████████▉| 21524/21538 [52:10<00:01,  9.48it/s]

✅ 00254_id06232_wavtolip (84 segments)
✅ 00254_id02310_wavtolip (135 segments)

Extracting audio: 100%|████████████████████████████▉| 21524/21538 [52:10<00:01,  9.48it/s]

✅ 00254_id05478_wavtolip (136 segments)

Extracting audio: 100%|████████████████████████████▉| 21526/21538 [52:11<00:01,  8.01it/s]

✅ 00254_id06254_wavtolip (99 segments)

Extracting audio: 100%|████████████████████████████▉| 21530/21538 [52:11<00:00,  9.29it/s]

✅ 00254_id06439_wavtolip (112 segments)
✅ 00254_id06437_wavtolip (123 segments)
✅ 00254_id06268_wavtolip (142 segments)
✅ 00028_id04530_wavtolip (74 segments)

Extracting audio: 100%|████████████████████████████▉| 21532/21538 [52:11<00:00,  9.90it/s]

✅ 00028_id02310_wavtolip (135 segments)
✅ 00028_id00747_wavtolip (154 segments)

Extracting audio: 100%|████████████████████████████▉| 21534/21538 [52:12<00:00,  9.14it/s]

✅ 00028_id04070_wavtolip (143 segments)
✅ 00028_id06254_wavtolip (99 segments)
✅ 00028_id06343_wavtolip (77 segments)

✅ 00028_id07008_wavtolip (132 segments)
✅ 00028_id07686_wavtolip (119 segments)

Extracting audio: 100%|█████████████████████████████| 21538/21538 [52:12<00:00,  6.88it/s]

✅ 00028_id07377_wavtolip (154 segments)

🎯 All videos processed successfully!

In [31]:
import torch
import torchaudio
import os
import re

def load_full_audio_from_chunks(folder_path, base_name):
    """
    Load multiple sequential audio chunks (e.g., video_frame00001.wav, video_frame00002.wav, ...)
    and concatenate them into one continuous waveform.
    
    Args:
        folder_path (str): Directory containing the audio files.
        base_name (str): Common prefix (e.g., "video_frame").
    
    Returns:
        waveform (Tensor): Combined audio waveform of shape [channels, total_samples].
        sample_rate (int): Sample rate (all chunks must have the same one).
    """

    # Find all matching chunk files
    files = [f for f in os.listdir(folder_path) if f.startswith(base_name) and f.endswith(".wav")]
    
    # Sort files numerically based on frame index
    files.sort(key=lambda x: int(re.findall(r'\d+', x)[-1]))

    waveforms = []
    sample_rate = None

    for f in files:
        path = os.path.join(folder_path, f)
        waveform, sr = torchaudio.load(path)

        if sample_rate is None:
            sample_rate = sr
        elif sample_rate != sr:
            raise ValueError(f"Sample rate mismatch in {f}: expected {sample_rate}, got {sr}")

        waveforms.append(waveform)

    # Concatenate along time dimension
    full_waveform = torch.cat(waveforms, dim=1)

    return full_waveform, sample_rate


import time

In [46]:
folder = "/home/manik/Downloads/alligned_audio/FakeVideo-FakeAudio/African/men/id00076"
base = "00109_2_id00166_wavtolip"  # prefix of files
start_time = time.time()
waveform, sr = load_full_audio_from_chunks(folder, base)
end_time = time.time()
print("Combined waveform shape:", waveform.shape)
print("Sample rate:", sr)
print(f"⏱ Time taken: {end_time - start_time:.3f} seconds")

Combined waveform shape: torch.Size([1, 67200])
Sample rate: 16000
⏱ Time taken: 0.045 seconds

In [47]:
np.save("testing_waveform", waveform.numpy())

In [55]:
start_time = time.time()

waveform_loaded = torch.from_numpy(np.load("testing_waveform.npy"))
end_time = time.time()
print(f"⏱ Time taken: {end_time - start_time:.3f} seconds")
print("Loaded waveform shape:", waveform_loaded.shape)

⏱ Time taken: 0.001 seconds
Loaded waveform shape: torch.Size([1, 67200])

In [52]:
import torchaudio

In [53]:
audio_path="/home/manik/Downloads/FakeAvCelebPreprocessed/FakeVideo-FakeAudio/African/men/id00076/00109_2_id00166_wavtolip.wav"
start_time = time.time()
audio, sample_rate = torchaudio.load(audio_path)
end_time = time.time()
print(f"⏱ Time taken: {end_time - start_time:.3f} seconds")
print("Audio shape:", audio.shape)

⏱ Time taken: 0.009 seconds
Audio shape: torch.Size([1, 67584])

In [62]:
ods_file="/home/manik/Downloads/FakeAvCelebPreprocessed/df_matching_frames.csv"
df = pd.read_csv(ods_file)
df.head()

,source,method,category,type,race,gender,path,split,full_path,num_frames,duration,difference
0,id00076,real,A,RealVideo-RealAudio,African,men,00109.mp4,train,/home/manik/Downloads/FakeAvCelebPreprocessed/...,251,10.048,0
1,id00166,real,A,RealVideo-RealAudio,African,men,00010.mp4,test,/home/manik/Downloads/FakeAvCelebPreprocessed/...,160,6.400,0
2,id00173,real,A,RealVideo-RealAudio,African,men,00118.mp4,train,/home/manik/Downloads/FakeAvCelebPreprocessed/...,149,6.016,0
3,id00366,real,A,RealVideo-RealAudio,African,men,00118.mp4,train,/home/manik/Downloads/FakeAvCelebPreprocessed/...,224,8.960,0
4,id00391,real,A,RealVideo-RealAudio,African,men,00052.mp4,val,/home/manik/Downloads/FakeAvCelebPreprocessed/...,300,12.032,0

In [63]:
df[df["full_path"]=="/home/manik/Downloads/FakeAvCelebPreprocessed/FakeVideo-FakeAudio/African/men/id00076/00109_2_id00166_wavtolip.mp4"]

,source,method,category,type,race,gender,path,split,full_path,num_frames,duration,difference
1735,id00076,faceswap-wav2lip,D,FakeVideo-FakeAudio,African,men,00109_2_id00166_wavtolip.mp4,train,/home/manik/Downloads/FakeAvCelebPreprocessed/...,102,4.224,0

In [64]:
import torchvision.io as io

In [65]:
video_path="/home/manik/Downloads/FakeAVCeleb_v1.2/FakeVideo-FakeAudio/African/men/id00076/00109_2_id00166_wavtolip.mp4"

video, audio, info = io.read_video(video_path, pts_unit="sec")

In [66]:
print(video.shape)
print(audio.shape)
print(info)

torch.Size([102, 224, 224, 3])
torch.Size([1, 67584])
{'video_fps': 25.0, 'audio_fps': 16000}

In [ ]:
target_duration = num_frames / video_fps  # seconds
target_audio_samples = int(round(target_duration * audio_fps))

Video duration from timestamps: 101/25 seconds

In [70]:
print(timestamps)

[Fraction(0, 1), Fraction(1, 25), Fraction(2, 25), Fraction(3, 25), Fraction(4, 25), Fraction(1, 5), Fraction(6, 25), Fraction(7, 25), Fraction(8, 25), Fraction(9, 25), Fraction(2, 5), Fraction(11, 25), Fraction(12, 25), Fraction(13, 25), Fraction(14, 25), Fraction(3, 5), Fraction(16, 25), Fraction(17, 25), Fraction(18, 25), Fraction(19, 25), Fraction(4, 5), Fraction(21, 25), Fraction(22, 25), Fraction(23, 25), Fraction(24, 25), Fraction(1, 1), Fraction(26, 25), Fraction(27, 25), Fraction(28, 25), Fraction(29, 25), Fraction(6, 5), Fraction(31, 25), Fraction(32, 25), Fraction(33, 25), Fraction(34, 25), Fraction(7, 5), Fraction(36, 25), Fraction(37, 25), Fraction(38, 25), Fraction(39, 25), Fraction(8, 5), Fraction(41, 25), Fraction(42, 25), Fraction(43, 25), Fraction(44, 25), Fraction(9, 5), Fraction(46, 25), Fraction(47, 25), Fraction(48, 25), Fraction(49, 25), Fraction(2, 1), Fraction(51, 25), Fraction(52, 25), Fraction(53, 25), Fraction(54, 25), Fraction(11, 5), Fraction(56, 25), Fraction(57, 25), Fraction(58, 25), Fraction(59, 25), Fraction(12, 5), Fraction(61, 25), Fraction(62, 25), Fraction(63, 25), Fraction(64, 25), Fraction(13, 5), Fraction(66, 25), Fraction(67, 25), Fraction(68, 25), Fraction(69, 25), Fraction(14, 5), Fraction(71, 25), Fraction(72, 25), Fraction(73, 25), Fraction(74, 25), Fraction(3, 1), Fraction(76, 25), Fraction(77, 25), Fraction(78, 25), Fraction(79, 25), Fraction(16, 5), Fraction(81, 25), Fraction(82, 25), Fraction(83, 25), Fraction(84, 25), Fraction(17, 5), Fraction(86, 25), Fraction(87, 25), Fraction(88, 25), Fraction(89, 25), Fraction(18, 5), Fraction(91, 25), Fraction(92, 25), Fraction(93, 25), Fraction(94, 25), Fraction(19, 5), Fraction(96, 25), Fraction(97, 25), Fraction(98, 25), Fraction(99, 25), Fraction(4, 1), Fraction(101, 25)]